In [2]:
#NUMPY
import numpy as np


In [5]:
#from python lists
#creating 1d array
list_1d=[1,2,3,4,5]
numpy_1d= np.array(list_1d)
print(list_1d)
print(numpy_1d)
print(type(list_1d))
print(type(numpy_1d))
#tuples
tuple_1d=(1,2,3,4,5,6,7)
array_1d=np.array(tuple_1d)
print(array_1d)


[1, 2, 3, 4, 5]
[1 2 3 4 5]
<class 'list'>
<class 'numpy.ndarray'>
[1 2 3 4 5 6 7]


In [8]:
#creating 2d array
list_2d=[[1,2,3,4,5],[6,7,8,9,10]]
array_2d=np.array(list_2d)
print(list_2d)
print(array_2d)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [14]:
#with specific datatype
list_1d=[1,5,7,9,3]
numpy_1d= np.array(list_1d, dtype= np.float32)
#numpy_1d= np.array([1,3,5,7], dtype= np.float32)
print(numpy_1d)

[1. 5. 7. 9. 3.]


In [21]:
#using builtin functions
zeros= np.zeros((3,3))
print(zeros)
ones=np.ones((2,3))
print(ones)
full_array= np.full((2,3), 2)
print(full_array)
my_arr=np.arange(5,50,2)
print(my_arr)
lin_arr = np.linspace(5, 20, 5)
print(lin_arr)
identity_arr= np.eye(3)
print(identity_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2]
 [2 2 2]]
[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]
[ 5.    8.75 12.5  16.25 20.  ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [32]:
#RANDOM ARRAYs
#we use np.random for random values in arrays
random_arr=np.random.rand(2,3)
print(random_arr)
random_array=np.random.randn(3) #r 2,3 any number 2 rows and 3 colums
print(random_array)
randn=np.random.randint(1,20,(3,2)) #3 rows and 2 columns
print(randn)
randn=np.random.randint(1,20,5) #5 columns
print(randn)
randomm=np.random.uniform(2,10,(2,3))
print(randomm)



[[0.48933988 0.31700227 0.50444035]
 [0.64188508 0.8287939  0.78821275]]
[ 0.10765244 -0.2639743  -0.61358563]
[[13 14]
 [ 7 19]
 [ 6 19]]
[14  9  9 18  6]
[[6.59126274 3.61997288 6.88389743]
 [6.14839117 2.77088331 9.40821592]]


In [33]:
#ARRAY attributes and methods
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Data type:", arr.dtype)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)

Shape: (2, 3)
Data type: int64
Size: 6
Dimensions: 2


In [38]:
#methods of array(max(), min(), reshape(), np.where(),np.unique
arr = np.array([1, 4, 2, 5, 3])
indices = np.where(arr > 3)
print("Indices:", indices)
print("Values:", arr[indices])
arr = np.array([1,2,5, 4, 2, 5, 3])
arr_unique= np.unique(arr)
print(arr_unique)
arr_reshape= np.arange(6).reshape(2,3)
print(arr_reshape)
arr=np.arange(6)
print(arr)


Indices: (array([1, 3]),)
Values: [4 5]
[1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [41]:
#Element wise operations
arr = np.array([1, 2, 3, 4])+5
print(arr)
print("Multiply by 3:", arr * 3)
print("Multiply by 5:", arr -7)
print("Division by 3:", arr / 3)
print("Square:", arr ** 2)

[6 7 8 9]
Multiply by 3: [18 21 24 27]
Multiply by 5: [-1  0  1  2]
Division by 3: [2.         2.33333333 2.66666667 3.        ]
Square: [36 49 64 81]


In [42]:
arr = np.array([1, 2, 3])
arr_copy = arr.copy()
arr_copy[0] = 99
print("Original:", arr)
print("Copy:", arr_copy)

Original: [1 2 3]
Copy: [99  2  3]


In [58]:
#concetination
arr1=[[1,2,3],[4,5,6]]
arr2=[[3,5,7],[7,8,9]]
array=np.array((arr1,arr2))
comb=np.concatenate((arr1,arr2), axis=0)
print(comb)
#splitting
array_split=np.array([1,2,3,4,5,6])
arrayy= np.split(array_split,2)
print(arrayy)
#slicing
array=[1,2,4,5,7,8,9,5,6]
array_slice=np.array(array)
print(array_slice[2:6])


[[1 2 3]
 [4 5 6]
 [3 5 7]
 [7 8 9]]
[array([1, 2, 3]), array([4, 5, 6])]
[4 5 7 8]


In [61]:
#broadcasting
arr = np.array([[1, 2], [3, 4]])
result = arr * 10
print(result)
matrix=[1,2,3]
mat=np.array(matrix)
vector=[4,5,6]
vec=np.array(vector)
add=mat+vec
print(add)

[[10 20]
 [30 40]]
[5 7 9]


In [2]:

a= np.array([[1,2,3], [4,5,6]])
a.shape

(2, 3)

In [7]:
a=np.array([1,2,3,4,5,6,])
print(a)

[1 2 3 4 5 6]


In [4]:
a[0]

np.int64(1)

In [5]:
a[0]=10

In [6]:
print(a)

[10  2  3  4  5  6]


In [11]:
a[:3]


array([1, 2, 3])

In [10]:
a[0:]

array([1, 2, 3, 4, 5, 6])

In [12]:
b=a[3:]
print(b)

[4 5 6]


In [15]:
b[0]= 40
print(b)

[40  5  6]


In [17]:
a=np.array([[1,2,3,4,5], [4,5,6,7,8],[8,90,55,10,15]])
print(a)

[[ 1  2  3  4  5]
 [ 4  5  6  7  8]
 [ 8 90 55 10 15]]


In [18]:
a[1,3]

np.int64(7)

In [19]:
a.dtype

dtype('int64')

In [24]:
np.zeros(3) #means specify shape of the array , 1-dimentional array with 3 elements

array([0., 0., 0.])

In [33]:
np.ones(2)

array([1., 1.])

In [28]:
np.empty(2)

array([0., 0.])

In [29]:
np.arange(4)

array([0, 1, 2, 3])

In [36]:
np.arange(2,100,2) #2 is the starting 10 is the stop value and 2 is the step size

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [38]:
arr=np.array([2,5,8,4,6,0,7,5,12,78,90])
np.sort(arr)

array([ 0,  2,  4,  5,  5,  6,  7,  8, 12, 78, 90])

In [62]:
#exercise
array=np.full((4,4),7)
print(array)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [63]:
array=np.random.rand(50,100)
print(array)

[[0.14341726 0.64745774 0.65959745 ... 0.06000053 0.87037901 0.73525037]
 [0.56567648 0.21429859 0.30622213 ... 0.1081736  0.54036288 0.01222555]
 [0.00756545 0.26255585 0.70731589 ... 0.66286043 0.09062104 0.38419723]
 ...
 [0.82112104 0.85392374 0.65352742 ... 0.75183312 0.11805666 0.21850805]
 [0.51855925 0.98495835 0.42169055 ... 0.19520933 0.98449017 0.69510365]
 [0.64229403 0.63762333 0.3793619  ... 0.80858696 0.52470797 0.95314262]]


In [67]:
x=[[1,2,3],[4,5,6],[7,8,9]]
arrayy=np.array(x)
print(arrayy+3)
print(arrayy-6)
print(arrayy*3)
print(arrayy/2)
print(arrayy**3)

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[-5 -4 -3]
 [-2 -1  0]
 [ 1  2  3]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[  1   8  27]
 [ 64 125 216]
 [343 512 729]]


In [71]:
arr=np.array([2,5,8,4,6,0,7,5,12,78,90])
x=np.where(arr<10,0,arr)
print(x)

[ 0  0  0  0  0  0  0  0 12 78 90]


In [5]:
# Exercise 1: Reshape an Array
#Create a 1D array with 12 elements using `np.arange()`, then reshape it into a 3x4 2D array.
array=np.arange(12).reshape(3,4)
print(array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
### Exercise 2: Generate Random Numbers
#Use `np.random.rand()` to create a 2x3 array filled with random numbers between 0 and 1.
array=np.random.rand(2,3)
print(array)

[[0.16424321 0.11492459 0.83524659]
 [0.37135656 0.70870831 0.91216052]]


In [9]:
### Exercise 3: Find Max and Min
#Given the array `arr = np.array([4, 2, 9, 1, 5])`, find its maximum and minimum values.
arr = np.array([4, 2, 9, 1, 5]).min()
print(arr)   
arr = np.array([4, 2, 9, 1, 5]).max()
print(arr.max())

1
9


In [10]:
### Exercise 4: Sum of Elements
#Compute the total sum of all elements in the array `arr = np.array([[1, 2], [3, 4]])`.
arr = np.array([[1, 2], [3, 4]]).sum()
print(arr)

10


In [11]:
### Exercise 5: Boolean Indexing
#Filter out all values greater than 5 from the array `arr = np.array([1, 6, 3, 8, 5])` using boolean indexing.
arr = np.array([1, 6, 3, 8, 5])
filtered_arr= arr[arr<=5]
print(filtered_arr)

[1 3 5]


In [17]:
### Exercise 6: Sum Along Axis
#For the array `arr = np.array([[1, 2, 3], [4, 5, 6]])`, compute the sum along each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.sum(axis=0)) #axis=0 specifies summing along each column


[5 7 9]


In [26]:
### Exercise 7: Conditional Replacement
#Use `np.where()` to replace all values less than 0 with 0 in the array `arr = np.array([-1, -2, -3, 4])`.
arr = np.array([-1, -2, -3, 4])
arr=np.where(arr<0,0,arr)
print(arr)


[0 0 0 4]


In [30]:
### Exercise 8: Concatenate Arrays
#Concatenate the arrays `arr1 = np.array([1, 2, 3])` and `arr2 = np.array([4, 5, 6])` horizontally (along columns).
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
combine=np.concatenate((arr1,arr2))
print(combine)

[1 2 3 4 5 6]


In [32]:
### Exercise 9: Split an Array
#Split the array `arr = np.arange(10)` into two equal parts.
arr = np.arange(10)
y=np.split(arr,2)
print(y)


[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [33]:
### Exercise 10: Unique Elements
#Find the unique elements in the array `arr = np.array([1, 2, 2, 3, 3, 3, 4])`.
arr = np.array([1, 2, 2, 3, 3, 3, 4])
y=np.unique(arr)
print(y)


[1 2 3 4]


In [34]:
## Exercise 11: Broadcasting
#Add a 1D array `arr1 = np.array([1, 2, 3])` to a 2D array `arr2 = np.array([[4, 5, 6], [7, 8, 9]])` using broadcasting.
arr1 = np.array([1, 2, 3])
arr2 = np.array([[4, 5, 6], [7, 8, 9]])
broadcast=arr1+arr2
print(broadcast)

[[ 5  7  9]
 [ 8 10 12]]


In [39]:
### Exercise 12: Views vs. Copies
#Create a view of the array `arr = np.array([1, 2, 3, 4])`, modify the view, and print both the view and the original array to observe the effect.
arr = np.array([1, 2, 3, 4])
copy_array=arr.copy()
copy_array[0]=25
print(arr)
print(copy_array)

[1 2 3 4]
[25  2  3  4]


In [44]:
### Exercise 13: Increase Dimensions
#Use `np.newaxis` to convert the 1D array `arr = np.array([1, 2, 3])` into a 2D array with shape (3, 1).
arr = np.array([1, 2, 3])
array=arr[:, np.newaxis] #adds a new dimension converting 1d array to 2d array
print(array.shape)
print(array)

(3, 1)
[[1]
 [2]
 [3]]


In [ ]:
### Exercise 14: Structured Array
#Create a structured array with fields `name` (string, max length 10), `age` (integer), and `height` (float). Add two entries: ("Alice", 25, 5.5) and ("Bob", 30, 6.0).